### ISSUE TITLE
failed to execute main script

### ISSUE THREAD

**Issue by FluffyDiscord** [MitsuhaYuki/yuki-emby-crack#5]
Can't run at all. Tried python 3.9 64bit and then 3.7.6 32bit

```log
PS C:\Users\Mossshine\Documents\dist> pyinstaller.exe .\main.exe
65 INFO: PyInstaller: 4.3
65 INFO: Python: 3.7.6
65 INFO: Platform: Windows-10-10.0.19041-SP0
66 INFO: wrote C:\Users\Mossshine\Documents\dist\main.spec
69 INFO: UPX is not available.
71 INFO: Extending PYTHONPATH with paths
['C:\\Users\\Mossshine\\Documents\\dist',
 'C:\\Users\\Mossshine\\Documents\\dist']
76 INFO: checking Analysis
76 INFO: Building Analysis because Analysis-00.toc is non existent
76 INFO: Initializing module dependency graph...
78 INFO: Caching module graph hooks...
87 WARNING: Several hooks defined for module 'win32ctypes.core'. Please take care they do not conflict.
91 INFO: Analyzing base_library.zip ...
2499 INFO: Caching module dependency graph...
2677 INFO: running Analysis Analysis-00.toc
2683 INFO: Adding Microsoft.Windows.Common-Controls to dependent assemblies of final executable
  required by c:\users\mossshine\appdata\local\programs\python\python37-32\python.exe
2783 INFO: Analyzing C:\Users\Mossshine\Documents\dist\main.exe
Traceback (most recent call last):
  File "c:\users\mossshine\appdata\local\programs\python\python37-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\mossshine\appdata\local\programs\python\python37-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Mossshine\AppData\Local\Programs\Python\Python37-32\Scripts\pyinstaller.exe\__main__.py", line 9, in <module>
  File "c:\users\mossshine\appdata\local\programs\python\python37-32\lib\site-packages\PyInstaller\__main__.py", line 114, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "c:\users\mossshine\appdata\local\programs\python\python37-32\lib\site-packages\PyInstaller\__main__.py", line 65, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "c:\users\mossshine\appdata\local\programs\python\python37-32\lib\site-packages\PyInstaller\building\build_main.py", line 737, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "c:\users\mossshine\appdata\local\programs\python\python37-32\lib\site-packages\PyInstaller\building\build_main.py", line 684, in build
    exec(code, spec_namespace)
  File "C:\Users\Mossshine\Documents\dist\main.spec", line 18, in <module>
    noarchive=False)
  File "c:\users\mossshine\appdata\local\programs\python\python37-32\lib\site-packages\PyInstaller\building\build_main.py", line 242, in __init__
    self.__postinit__()
  File "c:\users\mossshine\appdata\local\programs\python\python37-32\lib\site-packages\PyInstaller\building\datastruct.py", line 160, in __postinit__
    self.assemble()
  File "c:\users\mossshine\appdata\local\programs\python\python37-32\lib\site-packages\PyInstaller\building\build_main.py", line 414, in assemble
    priority_scripts.append(self.graph.run_script(script))
  File "c:\users\mossshine\appdata\local\programs\python\python37-32\lib\site-packages\PyInstaller\depend\analysis.py", line 304, in run_script
    pathname)
  File "c:\users\mossshine\appdata\local\programs\python\python37-32\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1411, in run_script
    contents = fp.read() + '\n'
  File "c:\users\mossshine\appdata\local\programs\python\python37-32\lib\codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x90 in position 2: invalid start byte
```

**Comment by MitsuhaYuki** [comment]
You don't need to install python because this exe is already a fully functional application for windows, just double click to run it.
